### ISSUE TITLE
Module Not found

### ISSUE THREAD

**Issue by Hariprabu94** [Kauto/better-sqlite3-helper#13]
Hi,
I am running better sqlite3 helper from my vue-cli project and am getting an error

**Module not found: Error: Can't resolve 'electron' in '/usr/test/project/node_modules/better-sqlite3-helper/src'**

Is electron manadatory to run better sqlite3 helper?

Nodejs version: 10.21.0
vue version: 4.5.6
Os: raspberrypi 4.19.97-v8+

Kindly assist.

**Comment by Kauto** [comment]
No, but there is a path detection included if the electron dependency exists. 

You should not get this error, because the code is surrounded by a try{}catch{}. Would be great if you could investigate this problem by yourself and add a pull request after you found the cause of it.

My guess is that you try to use this library in a browser? That will not work.
